name: build_docs
on: workflow_dispatch

jobs:
  build_docs:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1

      - name: install sandcastle
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install sandcastle --yes

      - name: build documentation
        run: msbuild script\cibuild_docs.msbuild -v:m
