name: build
on: [pull_request, workflow_dispatch]

jobs:
  test:
    name: test
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1
      - run: msbuild script\cibuild.msbuild -v:m
