name: build_docs
on: workflow_dispatch

jobs:
  build_docs:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1

      - name: install sandcastle
        run: choco --yes install sandcastle

      - name: build documentation
        run: msbuild script\cibuild_docs.msbuild -v:m
